(function(){
'use strict';
const actionNames={INSERT:'създаде',UPDATE:'редактира',DELETE:'изтри'};
const entityNames={sessions:'тренировка',registrations:'записване',site_settings:'настройка на сайта',payment_adjustments:'корекция на плащане',payment_config:'такси',registration_payment_overrides:'тарифа на участник',manual_payment_sessions:'външна тренировка',manual_payment_templates:'шаблон за външна тренировка',training_templates:'шаблон за тренировка',app_admins:'административен профил'};
const fieldNames={date:'Дата',time:'Час',title:'Заглавие',trainer:'Треньор',location:'Място',duration:'Продължителност',capacity:'Максимални места',booking_closed:'Записването е затворено',force_open:'Отворено веднага',booking_days:'Отваряне дни преди',booking_close_hours:'Спиране часове преди',announcement:'Съобщение',description:'Описание',session_id:'Тренировка',name:'Име',has_multisport:'MultiSport',booked_by:'Записан от',pending:'Изчакващ',cancelled_at:'Отписан на',key:'Настройка',value:'Стойност',extra_individual:'Добавени индивидуални',extra_multisport:'Добавени MultiSport',extra_card8:'Добавени карта 8',extra_card12:'Добавени карта 12',multisport_rate:'Цена MultiSport',individual_rate:'Цена без MultiSport',card8_rate:'Цена карта 8',card12_rate:'Цена карта 12',payment_type:'Тарифа',template_id:'Шаблон',multisport_count:'Брой MultiSport',individual_count:'Брой без MultiSport',card8_count:'Брой карта 8',card12_count:'Брой карта 12',sort_order:'Подредба',display_name:'Име',email:'Имейл',is_owner:'Роля Owner',active:'Активен профил',can_view_history:'История',audit_color:'Цвят в историята'};
const restorables=new Set(['sessions','registrations','site_settings','payment_adjustments','payment_config','registration_payment_overrides','manual_payment_sessions','manual_payment_templates','training_templates']);
let context=null,loading=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
function fallbackColor(email){let hash=0;for(const char of String(email||'admin'))hash=(hash*31+char.charCodeAt(0))>>>0;return `hsl(${hash%360} 58% 38%)`}
function colorWithAlpha(color){if(/^#[0-9a-f]{6}$/i.test(color||''))return color+'14';return 'rgba(23,111,80,.07)'}
function valueName(value,field){if(value===null||value===undefined||value==='')return '—';if(value===true||value==='true')return 'Да';if(value===false||value==='false')return 'Не';const payment={multisport:'MultiSport',individual:'Без MultiSport',card8:'Карта 8',card12:'Карта 12'};if(field==='payment_type'&&payment[value])return payment[value];if(field==='is_owner')return valueName(value)==='Да'?'Owner':'Администратор';if(typeof value==='object')return JSON.stringify(value);return String(value)}
function timeSofia(value){try{return new Intl.DateTimeFormat('bg-BG',{timeZone:'Europe/Sofia',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value))}catch{return String(value||'')}}
function changeMarkup(changes){const entries=Object.entries(changes||{});if(!entries.length)return '<div class="historyChange"><span>Няма променени проследявани полета.</span></div>';return entries.map(([field,change])=>`<div class="historyChange"><strong>${esc(fieldNames[field]||field)}</strong><span><span class="historyFrom">${esc(valueName(change?.from,field))}</span><span class="historyArrow">→</span><span class="historyTo">${esc(valueName(change?.to,field))}</span></span></div>`).join('')}
function renderLogs(logs,deleted){const list=document.getElementById('historyList');const deletedKeys=new Set((deleted||[]).map(item=>`${item.entity_type}:${item.entity_id}`));if(!logs.length){list.innerHTML='<div class="historyState">Все още няма записани административни действия.</div>';return}list.innerHTML=logs.map(log=>{const details=log.details||{},color=log.actor_color||fallbackColor(log.actor_email),canRestore=context?.is_owner&&log.action==='DELETE'&&restorables.has(log.entity_type)&&deletedKeys.has(`${log.entity_type}:${log.entity_id}`);return `<article class="historyEntry" style="--audit-color:${esc(color)};--audit-bg:${esc(colorWithAlpha(color))}"><div class="historyEntryTop"><div class="historyActor"><strong>${esc(log.actor_name||'Администратор')}</strong><span>${esc(log.actor_email)}</span></div><time class="historyTime">${esc(timeSofia(log.created_at))}</time></div><div class="historySentence">${esc(actionNames[log.action]||log.action)} ${esc(entityNames[log.entity_type]||log.entity_type)} <b>„${esc(details.label||log.entity_id||'Без име')}“</b></div><div class="historyChanges">${changeMarkup(details.changes)}</div>${canRestore?`<button class="historyRestore" type="button" onclick="restoreHistoryItem('${esc(log.entity_type)}','${esc(log.entity_id)}')">↶ Възстанови</button>`:''}</article>`}).join('')}
function ensureProfilesSection(){if(document.getElementById('profilesView'))return;const historyTab=document.getElementById('historyTab');historyTab.insertAdjacentHTML('afterend','<button class="adminSectionTab" id="profilesTab" type="button" onclick="switchAdminSection(\'profiles\')" hidden>Профили</button>');const historyView=document.getElementById('historyView');historyView.insertAdjacentHTML('afterend','<section class="profilesView" id="profilesView" aria-label="Управление на административни профили"><div class="profilesHeader"><div><h2>Профили</h2><p>Всеки активен профил има пълен Owner достъп.</p></div></div></section>');const wrap=document.getElementById('historyProfiles');document.getElementById('profilesView').appendChild(wrap);wrap.hidden=false;wrap.querySelector('h3').textContent='Управление на профилите';wrap.querySelector('p').textContent='Добавяне на нов профил и редакция на името, цвета и активния достъп.';const addForm=wrap.querySelector('.historyAddProfile');const addDetails=document.createElement('details');addDetails.className='profileAddDetails';addDetails.innerHTML='<summary>＋ Добави нов профил</summary>';addForm.before(addDetails);addDetails.appendChild(addForm);const access=document.getElementById('historyNewAccess');if(access){access.checked=true;access.closest('label').hidden=true}}
async function loadProfiles(){const list=document.getElementById('historyProfileList');if(!context?.is_owner){list.innerHTML='<div class="historyState">Нямате достъп до профилите.</div>';return}list.innerHTML='<div class="historyState">Зареждане…</div>';const result=await window.nikiAdmin.adminProfiles();if(result.error){list.innerHTML='<div class="historyState">Профилите не могат да бъдат заредени.</div>';return}list.innerHTML=(result.data||[]).map(profile=>`<details class="profileEditor" data-user-id="${esc(profile.user_id)}"><summary><div class="historyProfileEmail"><strong>${esc(profile.display_name||profile.email)}</strong><span>${esc(profile.email)}</span><i class="historyRole">Owner</i></div><span class="profileEditLabel">Редактирай</span></summary><div class="profileEditorBody"><label><span>Име</span><input class="profileName" type="text" maxlength="80" value="${esc(profile.display_name||'')}" aria-label="Име"></label><label><span>Цвят в историята</span><input class="profileColor" type="color" value="${esc(profile.audit_color||'#176F50')}" aria-label="Цвят"></label><label class="profileActiveLabel"><input class="profileActive" type="checkbox" ${profile.active?'checked':''}> Активен профил</label><button type="button" onclick="saveHistoryProfile('${esc(profile.user_id)}')">Запази промените</button></div></details>`).join('')||'<div class="historyState">Няма административни профили.</div>'}
window.loadAdminProfiles=loadProfiles;
window.loadAdminHistory=async function(){if(loading||!context?.can_view_history)return;loading=true;const button=document.getElementById('historyRefresh');button.disabled=true;document.getElementById('historyList').innerHTML='<div class="historyState">Зареждане…</div>';const result=await window.nikiAdmin.historyLogs();loading=false;button.disabled=false;if(result.error){document.getElementById('historyList').innerHTML='<div class="historyState">Историята не може да бъде заредена. Проверете дали SQL миграцията е изпълнена.</div>';return}context=result.context||context;renderLogs(result.data||[],result.deleted||[])};
window.initializeAdminHistory=async function(){if(!window.nikiAdmin)return;ensureProfilesSection();const result=await window.nikiAdmin.historyContext();const tab=document.getElementById('historyTab'),profilesTab=document.getElementById('profilesTab');if(result.error||!result.data?.can_view_history){tab.hidden=true;profilesTab.hidden=true;if(document.getElementById('adminShell').classList.contains('historyMode')||document.getElementById('adminShell').classList.contains('profilesMode'))window.switchAdminSection('training');return}context=result.data;tab.hidden=false;profilesTab.hidden=false;let wanted='';try{wanted=localStorage.getItem('nikiAdminActiveSection')}catch{}if(wanted==='history'||wanted==='profiles')window.switchAdminSection(wanted)};
window.restoreHistoryItem=async function(entityType,entityId){if(!context?.is_owner||!confirm('Сигурни ли сте, че искате да възстановите този запис?'))return;const result=await window.nikiAdmin.restoreDeletedItem(entityType,entityId);if(result.error){window.showToast?.('Записът не беше възстановен.');return}await window.nikiAdmin.refresh();window.renderAll?.();await window.loadAdminHistory();window.showToast?.(`Възстановени записи: ${result.data?.restored_count||1}`)};
window.saveHistoryProfile=async function(userId){const row=document.querySelector(`.profileEditor[data-user-id="${CSS.escape(userId)}"]`);if(!row)return;const result=await window.nikiAdmin.updateAdminProfile({userId,displayName:row.querySelector('.profileName').value.trim(),auditColor:row.querySelector('.profileColor').value,canViewHistory:true,active:row.querySelector('.profileActive').checked});if(result.error){window.showToast?.('Профилът не беше запазен. Собственият активен профил не може да бъде изключен.');return}window.showToast?.('Профилът е запазен.');await window.loadAdminProfiles()};
window.addHistoryProfile=async function(){const email=document.getElementById('historyNewEmail').value.trim(),displayName=document.getElementById('historyNewName').value.trim(),auditColor=document.getElementById('historyNewColor').value;if(!email){window.showToast?.('Въведете имейл.');return}const result=await window.nikiAdmin.addAdminProfile({email,displayName,auditColor,canViewHistory:true});if(result.error){window.showToast?.('Потребителят трябва първо да съществува в Supabase Authentication.');return}document.getElementById('historyNewEmail').value='';document.getElementById('historyNewName').value='';document.querySelector('.profileAddDetails')?.removeAttribute('open');window.showToast?.('Административният профил е добавен с пълен достъп.');await window.loadAdminProfiles()};
})();
